
#
# Module Manifest for Module 'PowerShellBooks.psd1
#
# This manifest file is a PowerShell hashtable with all technical requirements for this module
# This module was autogenerated by ISESteroids (http://www.isesteroids.com)
#
# Generated: 2019-07-14
#

@{

# Module Loader File
RootModule = 'loader.psm1'

# Version Number
ModuleVersion = '1.0'

# Unique Module ID
GUID = '7dadb8b4-4369-4772-84d8-357005c07543'

# Module Author
Author = 'Andreas Nick'

# Company
CompanyName = 'Andreas Nick'

# Copyright
Copyright = '(c) 2019 Andreas. All rights reserved for the module (PowerShell) the MIT license is valid. The used library itextsharp is licensed under the GNU Affero General Public License version 3.'

# Module Description
Description = 'Create a PowerShell commandlet pdf book'

# Minimum PowerShell Version Required
PowerShellVersion = ''

# Name of Required PowerShell Host
PowerShellHostName = ''

# Minimum Host Version Required
PowerShellHostVersion = ''

# Minimum .NET Framework-Version
DotNetFrameworkVersion = ''

# Minimum CLR (Common Language Runtime) Version
CLRVersion = ''

# Processor Architecture Required (X86, Amd64, IA64)
ProcessorArchitecture = ''

# Required Modules (will load before this module loads)
RequiredModules = @()

# Required Assemblies
RequiredAssemblies = @()

# PowerShell Scripts (.ps1) that need to be executed before this module loads
ScriptsToProcess = @()

# Type files (.ps1xml) that need to be loaded when this module loads
TypesToProcess = @()

# Format files (.ps1xml) that need to be loaded when this module loads
FormatsToProcess = @()

# 
NestedModules = @()

# List of exportable functions
FunctionsToExport = 'New-PowerShellBook', 'New-PowerShellCommandDocumentation', 'New-CombineMultiplePDFs'

# List of exportable cmdlets
CmdletsToExport = ''

# List of exportable variables
VariablesToExport = '*'

# List of exportable aliases
AliasesToExport = '*'

# List of all modules contained in this module
ModuleList = @()

# List of all files contained in this module
FileList = @()

# Private data that needs to be passed to this module
PrivateData = ''

}